### ISSUE TITLE
Juju "getting started" link broken

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/landscape-docs#115]
The "getting started" link on [landscape-install-juju](https://docs.ubuntu.com/landscape/en/landscape-install-juju) leads to 404:

https://jujucharms.com/get-started

**Comment by anthonydillon** [comment]
Also added a redirect on jaas.ai to cover other links in the future: https://github.com/canonical-web-and-design/jaas.ai/pull/506
