### ISSUE TITLE
http://ppa.launchpad.net/landscape/19.10/ubuntu focal Release               404  Not Found [IP: 91.189.95.83 80]

### ISSUE THREAD

**Issue by jacque8080** [canonical-web-and-design/landscape-docs#124]
I am unable to find the package when I run the following:

  sudo apt-get install landscape-server-quickstart

I think it is related to the 404 error below:
   Err:6 http://ppa.launchpad.net/landscape/19.10/ubuntu focal Release  404  Not Found [IP: 91.189.95.83 80]

> x@x:~$ sudo add-apt-repository ppa:landscape/19.10
>  October 2019 release of Landscape
>  More info: https://launchpad.net/~landscape/+archive/ubuntu/19.10
> Press [ENTER] to continue or Ctrl-c to cancel adding it.
> 
> Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
> Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease                      
> Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
> Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease            
> Ign:5 http://ppa.launchpad.net/landscape/19.10/ubuntu focal InRelease          
> Err:6 http://ppa.launchpad.net/landscape/19.10/ubuntu focal Release            
>   404  Not Found [IP: 91.189.95.83 80]
> Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease               
> Hit:8 https://packages.microsoft.com/repos/ms-teams stable InRelease         
> Reading package lists... Done                          
> E: The repository 'http://ppa.launchpad.net/landscape/19.10/ubuntu focal Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by anthonydillon** [comment]
@jacque8080 Thank you for reporting this issue to us but it's not really a doc issue, and it's because landscape-onprem does not support installing on that series.
