### ISSUE TITLE
Packages upgrades remains indefinitely in "in progress" state

### ISSUE THREAD

**Issue by pmilano** [canonical-web-and-design/landscape-docs#129]
Hi there,

We are using Landscape with 35 workstations.
Since a week, package upgrades activities stopped working properly. When we launch them through Landscape they remain indefinitely under "in progress" state. No more details nor errors are showed.
We tried updating manually and locally some workstations but the behaviour remains the same.

Since there is no help option in our Landscape Console, we are triying to find help through this way.

**Comment by Roadmaster** [comment]
Closing - this is not the proper channel to get landscape support. I'll reply to the email you sent me with more information.

**Comment by amardeepk2** [comment]
Hi Team,

I can see my sync activity shows in progress as 0 and its not showing any progress.

landscape-api get-activities --query id:38 --json | jq
[
  {
    "children": [],
    "schedule_after_time": null,
    "creator": {
      "id": 1,
      "name": "landscape-admin",
      "email": "*************@gmail.com"
    },
    "result_text": null,
    "pocket_id": 4,
    "creation_time": "2023-02-05T20:19:25Z",
    "schedule_before_time": null,
    "summary": "Sync pocket 'security' of series 'jammy' in distribution 'ubuntu'",
    "completion_time": null,
    "modification_time": "2023-02-05T20:19:25Z",
    "parent_id": 37,
    "pocket_name": "security",
    "activity_status": "delivered",
    "progress": 0,
    "type": "SyncPocketRequest",
    "id": 38,
    "result_code": null
